//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSenDa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DanhGia = new HashSet<DanhGia>();
            this.DiaChi = new HashSet<DiaChi>();
            this.DonHang = new HashSet<DonHang>();
        }
        [DisplayName("Mã khách hàng")]
        [Required(ErrorMessage = "Mã khách hàng không được trống...")]
        public int IDKhachHang { get; set; }
        [DisplayName("Mã loại tài khoản")]
        [Required(ErrorMessage = "Mã loại tài khoản không được trống...")]
        public int IDLoaiTaiKhoan { get; set; }
        [DisplayName("Tên tài khoản")]
        [Required(ErrorMessage = "Tên tài khoản không được trống...")]
        public string TenTaiKhoan { get; set; }
        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "Mật khẩu không được trống...")]
        public string MatKhau { get; set; }
        [DisplayName("Tên khách hàng")]
        [Required(ErrorMessage = "Tên khách hàng không được trống...")]
        public string TenKhachHang { get; set; }
        [DisplayName("Số điện thoại")]
        [Required(ErrorMessage = "Số điện thoại không được trống...")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Số điện thoại bắt đầu là 0, không bao gồm chữ, gồm 10 số. ")]
        public string SoDienThoai { get; set; }
        [DisplayName("CMND")]
        [Required(ErrorMessage = "Chứng minh nhân dân không được trống...")]
        public string CMND { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "Email không được trống...")]
        [EmailAddress(ErrorMessage = "Email không đúng định dạng. Ví dụ: example@gmail.com")]
        public string Email { get; set; }
        [DisplayName("Điểm tích lũy")]
        [Required(ErrorMessage = "Điểm tích lũy không được trống...")]
        public Nullable<int> DiemTichLuy { get; set; }
        [DisplayName("Ảnh đại diện")]
        [Required(ErrorMessage = "Ảnh đại diện không được trống...")]
        public string AnhDaiDien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiaChi> DiaChi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHang { get; set; }
        public virtual LoaiTaiKhoan LoaiTaiKhoan { get; set; }
    }
}
