//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSenDa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.DanhGia = new HashSet<DanhGia>();
            this.NhapKho = new HashSet<NhapKho>();
        }
        [DisplayName("Mã sản phẩm")]
        [Required(ErrorMessage = "Mã sản phẩm không được trống...")]
        public int IDSanPham { get; set; }
        [DisplayName("Mã loại sản phẩm")]
        [Required(ErrorMessage = "Mã loại sản phẩm không được trống...")]
        public int IDLoaiSanPham { get; set; }
        [DisplayName("Mã loại sen đá")]
        [Required(ErrorMessage = "Mã loại sen đá không được trống...")]
        public Nullable<int> IDLoaiSenDa { get; set; }
        [DisplayName("Mã loại chậu cây")]
        [Required(ErrorMessage = "Mã loại chậu cây không được trống...")]
        public Nullable<int> IDLoaiChauCay { get; set; }
        [DisplayName("Mã loại giá thẻ")]
        [Required(ErrorMessage = "Mã loại giá thẻ không được trống...")]
        public Nullable<int> IDLoaiGiaThe { get; set; }
        [DisplayName("Mã khuyến mãi")]
        [Required(ErrorMessage = "Mã khuyến mãi không được trống...")]
        public Nullable<int> IDKhuyenMai { get; set; }
        [DisplayName("Tên sản phẩm")]
        [Required(ErrorMessage = "Tên sản phẩm không được trống...")]
        public string TenSanPham { get; set; }
        [DisplayName("Hình")]
        [Required(ErrorMessage = "Hình không được trống...")]
        public string Hinh { get; set; }
        [DisplayName("Hình 1")]
        [Required(ErrorMessage = "Hình 1 không được trống...")]
        public string Hinh1 { get; set; }
        [DisplayName("Hình 2")]
        [Required(ErrorMessage = "Hình 2 không được trống...")]
        public string Hinh2 { get; set; }
        [DisplayName("Hình 3")]
        [Required(ErrorMessage = "Hình 3 không được trống...")]
        public string Hinh3 { get; set; }
        [DisplayName("Mô tả")]
        [Required(ErrorMessage = "Mô tả không được trống...")]
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGia { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual LoaiChauCay LoaiChauCay { get; set; }
        public virtual LoaiGiaThe LoaiGiaThe { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual LoaiSenDa LoaiSenDa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhapKho> NhapKho { get; set; }
    }
}
